IBM/secrets-manager-java-sdk

modules/coverage-reports/pom.xml

https://issues.sonatype.org/browse/NEXUS-19853

remove skip flag - sonatype issue

---

README.md
modules/common/pom.xml
modules/coverage-reports/pom.xml
modules/secrets-manager/pom.xml
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/SecretsManager.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/model/GetConfig.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/model/IAMSecretEngineRootConfig.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/model/ListAllSecretsOptions.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/model/SecretMetadata.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/model/UpdateSecretOptions.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/SecretsManagerIntegrationTest.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/SecretsManagerTest.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/model/GetConfigTest.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/model/IAMSecretEngineRootConfigTest.java
pom.xml

API update

---

modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/SecretsManagerIntegrationTest.java

Add Cleanup to Tests and enable parallel test runs

Add Cleanup to Tests and enable parallel test runs

---

README.md
modules/common/pom.xml
modules/coverage-reports/pom.xml
modules/secrets-manager/pom.xml
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/SecretsManager.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/model/PrivateCertificateSecretResource.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/model/RotatePrivateCertBodyWithCsr.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/model/SecretAction.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/model/SecretResource.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/SecretsManagerTest.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/model/PrivateCertificateSecretResourceTest.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v1/model/RotatePrivateCertBodyWithCsrTest.java
pom.xml

Signed-off-by: haims <haims@il.ibm.com>

User-provided CSR

---

.bumpversion.cfg
.github/workflows/create-and-publish-release.yml
.github/workflows/run-tests.yml
.releaserc

fix: New workflow

---

README.md
modules/common/pom.xml
modules/coverage-reports/pom.xml
modules/secrets-manager/pom.xml
pom.xml

patch: align versions

---

README.md

patch: test workflow

---

.github/workflows/create-and-publish-release.yml

patch: New workflow

---

.github/workflows/create-and-publish-release.yml
.github/workflows/run-tests.yml
.releaserc
README.md

release: update workflow and README.md

release: update workflow and README.md

---

.releaserc

release: New workflow

---

pom.xml

update dependency sdk-core-version to 9.17.4

release: update dependencies

---

.github/workflows/create-and-publish-release.yml

release: fix duplicate publish

release: fix duplicate publish

---

.github/workflows/create-and-publish-release.yml
.github/workflows/run-tests.yml
.releaserc
README.md

release: test workflow

---

.github/release.yaml
.github/workflows/create-and-publish-release.yml

- fixed issue where the publish step was parallel to the release
- add release notes to new releases

release: fix workflow steps

---

.github/workflows/codeql-analysis.yml
.github/workflows/create-and-publish-release.yml

1. update the tests workflow version to mitigate warnings
2. test fixing for the merging workflow

New workflow

---

README.md
package-lock.json

Update dependencies to remove vulnerabilities

[ci skip] update dependencies

---

README.md

major: new SM v2 API release

---

README.md

major: new SM v2 release

---

examples/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/SecretsManagerExamples.java
modules/examples/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/SecretsManagerExamples.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/SecretsManagerIT.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/SecretsManagerTest.java

Update expiration dates for fixing unit tests.

Update expiration dates for fixing unit tests.

---

modules/examples/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/SecretsManagerExamples.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/SecretsManager.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/ListSecretsOptions.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/Secret.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/SecretMetadata.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/SecretMetadataPatch.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/SecretPrototype.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/SecretsManagerIT.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/SecretsManagerTest.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/IAMCredentialsSecretMetadataTest.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/IAMCredentialsSecretTest.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/ListSecretsOptionsTest.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/ServiceCredentialsSecretMetadataTest.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/ServiceCredentialsSecretTest.java

- Add List filters: `secret_types`, `match_all_labels`
- Add Expiration date field to `iam_credentials` and `service_credentials` API responses

patch: API enhancements

---

README.md
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/SecretsManager.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/ConfigurationAction.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/ConfigurationActionPrototype.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/PrivateCertificateConfigurationActionRevoke.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/PrivateCertificateConfigurationActionRevokePrototype.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/PrivateCertificateConfigurationActionRotate.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/PrivateCertificateConfigurationActionRotateCRL.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/PrivateCertificateConfigurationActionRotateCRLPrototype.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/PrivateCertificateConfigurationActionRotatePrototype.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/PrivateCertificateConfigurationActionSetSigned.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/PrivateCertificateConfigurationActionSetSignedPrototype.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/PrivateCertificateConfigurationActionSignCSR.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/PrivateCertificateConfigurationActionSignCSRPrototype.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/PrivateCertificateConfigurationActionSignIntermediate.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/PrivateCertificateConfigurationActionSignIntermediatePrototype.java
modules/secrets-manager/src/main/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/PrivateCertificateConfigurationRotateAction.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/SecretsManagerTest.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/PrivateCertificateConfigurationActionRotatePrototypeTest.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/PrivateCertificateConfigurationActionRotateTest.java
modules/secrets-manager/src/test/java/com/ibm/cloud/secrets_manager_sdk/secrets_manager/v2/model/PrivateCertificateConfigurationRotateActionTest.java

add private cert intermediate rotate API

patch: support for intermediate CA certificates rotation
